import { Geist, Geist_Mono } from "next/font/google";
import { NextIntlClientProvider } from 'next-intl';
import { notFound } from 'next/navigation';
import { setRequestLocale } from 'next-intl/server';
import Header from '@/components/Header/Header';
import LoginModal from '@/components/LoginModal/LoginModal';
import Providers from '@/components/Providers/Providers';
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children, params }) {
  const { locale } = await params;


  console.log('locale:', locale)

  if (!['en', 'ua'].includes(locale)) {
    notFound();
  }

  setRequestLocale(locale);

  return (
    <html lang={locale}>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Providers>
          <NextIntlClientProvider>
            <div style={{ maxWidth: '100vw', overflowX: 'hidden' }}>
              <Header />
              {children}
              <LoginModal />
            </div>
          </NextIntlClientProvider>
        </Providers>
      </body>
    </html>
  );
}
